### ISSUE TITLE
Improve experience on a phone

### ISSUE THREAD

**Issue by rkversion** [kartta-labs/kscope#23]
One can pull up 3D view on a phone, but there is no way to move around. 
At the very least there should be a notice alerting user about the missing functionality.

**Comment by embeepea** [comment]
https://github.com/kartta-labs/kscope/pull/27 improves phone experience more; 1-finger drag to move, 2-finger drag to look around, now works both at street level and in birds eye view.

**Comment by embeepea** [comment]
also tested on a pixelbook

**Comment by embeepea** [comment]
There's still room for improvement of the 3D experience on mobile, but hopefully this is a usable minimal implementation, soI'm going to close this issue for now.  If there are any specific requests / suggestions for improvement, please open new issues for them.
